--1
SELECT CURDATE() ,
CURRENT_DATE() ,
CURTIME() ,
CURRENT_TIME() ,
NOW() ,
CURRENT_TIMESTAMP();

--2
SELECT 
YEAR(ORDER_DATE) ,
MONTH(ORDER_DATE) ,
DAY(ORDER_DATE)
FROM orders;

--3
SELECT 
EXTRACT(YEAR FROM ORDER_DATE),
EXTRACT(MONTH FROM ORDER_DATE)
FROM orders;

--4
SELECT MONTHNAME(ORDER_DATE) ,
DAYNAME(ORDER_DATE) 
FROM orders;

--5
SELECT DAYNAME(ORDER_DATE) ,
WEEKDAY(ORDER_DATE) ,
DAYOFWEEK(ORDER_DATE)
FROM orders;

--6
SELECT ORDER_ID ,
ORDER_DATE ,
DAYNAME(ORDER_DATE) AS Day
FROM orders
WHERE DAYNAME(ORDER_DATE) IN ('Saturday' , 'Sunday');

--7
SELECT ORDER_ID ,
ORDER_DATE ,
DAYNAME(ORDER_DATE) AS Day
FROM orders
WHERE DAYOFWEEK(ORDER_DATE) BETWEEN 2 AND 6;

--8
SELECT DATE_ADD(ORDER_DATE , INTERVAL 5 DAY) AS DATE_ADDED,
DATE_SUB(ORDER_DATE , INTERVAL 1 YEAR) AS YEAR_SUBTRACTED,
DATE_ADD(ORDER_DATE , INTERVAL 3 MONTH) AS MONTH_ADDED
FROM orders;

--9
SELECT DATEDIFF(DELIVERY_DATE , ORDER_DATE) AS DELIVERY_DAYS
FROM orders;

--10
SELECT TIMESTAMPDIFF(MONTH , ORDER_DATE , DELIVERY_DATE ) AS MONTHS_DIFF,
TIMESTAMPDIFF(DAY , ORDER_DATE , DELIVERY_DATE ) AS DAYS_DIFF
FROM orders;

--11
SELECT DATE_SUB(ORDER_DATE , INTERVAL DAY(ORDER_DATE) -1 DAY) AS FIRST_DAY 
FROM orders;

--12
SELECT LAST_DAY(ORDER_DATE)
FROM orders;

--13
SELECT DATE_FORMAT(ORDER_DATE , '%d-%m-%Y')
FROM orders;

--14
SELECT STR_TO_DATE('15-01-2024' , '%d-%m-%Y');

--15
SELECT DATE_FORMAT(ORDER_DATE , '%d-%m-%Y %H:%i:%s')
FROM orders;

--16
SELECT order_date ,
CASE 
WHEN MONTH(ORDER_DATE) >=4
THEN CONCAT(
  YEAR(ORDER_DATE),'-' ,YEAR(ORDER_DATE)+1
) 
ELSE CONCAT(
  YEAR(ORDER_DATE)-1 , '-' ,YEAR(ORDER_DATE)
)
END AS FINANCIAL_YEAR
FROM orders;
