-- QUERY11
SELECT 
LOWER(EMP_NAME) AS EMP_NAME,
ROUND(SALARY,2) AS ROUNDED_SALARY,
TRUNCATE(SALARY,2) AS TRUNCATED_SALARY,
ABS(ROUND(SALARY,2) - TRUNCATE(SALARY,2)) AS PRECISION_DIFFERENCE,
MONTHNAME(revision_date) AS revision_month,
CASE 
WHEN ABS(ROUND(SALARY,2) - TRUNCATE(SALARY,2)) > 0
THEN 'PRECISION LOSS'
ELSE 'STABLE'
END AS PRECISION_CHECK
FROM salary_precision;


-- QUERY12
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
POWER((1+GROWTH_RATE/100), YEARS_PROJECTED) * CURRENT_SALARY AS FUTURE_SALARY,
ROUND(POWER((1+GROWTH_RATE/100), YEARS_PROJECTED) * CURRENT_SALARY) AS ROUNDED_PROJECTION,
GROWTH_RATE AS GROWTH_PERCENTAGE,
CASE 
WHEN ((POWER((1+GROWTH_RATE/100), YEARS_PROJECTED) - 1) * 100) > 50 THEN 'RAPID GROWTH'
WHEN ((POWER((1+GROWTH_RATE/100), YEARS_PROJECTED) - 1) * 100) BETWEEN 20 AND 50 THEN 'MODERATE'
ELSE 'STABLE'
END AS GROWTH_STATUS
FROM salary_growth;


-- QUERY13
SELECT 
LOWER(EMP_NAME) AS EMP_NAME,
SALARY AS ORIGINAL_SALARY,
REVERSE(SALARY) AS REVERSE_SALARY,
DAYNAME(CHECK_DATE) AS Check_Day,
CASE 
WHEN salary = REVERSE(salary) THEN 'Symmetric'
ELSE 'Non-Symmetric'
END AS symmetry_status
FROM salary_symmetry;


-- QUERY14
SELECT 
CONCAT(UPPER(LEFT(EMP_NAME,1)), LOWER(SUBSTRING(EMP_NAME,2))) AS EMPLOYEE_NAME,
ROUND(SALARY) AS ROUNDED_SALARY,
DAYNAME(PAYMENT_DATE) AS DAY_NAME,
YEAR(PAYMENT_DATE) AS PAYMENT_YEAR,
CASE 
WHEN YEAR(PAYMENT_DATE)%4=0 AND YEAR(PAYMENT_DATE)%100!=0 THEN 'Leap Year Payment'
ELSE 'Normal Payment'
END AS LEAP_STATUS
FROM leap_salary;


-- QUERY15
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
DATEDIFF(ACTUAL_CREDIT, EXPECTED_CREDIT) AS DELAY_DAYS,
ROUND(SALARY) AS ROUNDED_SALARY,
DAYNAME(ACTUAL_CREDIT) AS CREDIT_DAY,
CASE 
WHEN DATEDIFF(ACTUAL_CREDIT, EXPECTED_CREDIT) > 5 THEN 'SEVERE DELAY'
WHEN DATEDIFF(ACTUAL_CREDIT, EXPECTED_CREDIT) BETWEEN 1 AND 5 THEN 'MINOR DELAY'
ELSE 'ON TIME'
END AS DELAY_STATUS
FROM salary_credit_audit;


-- QUERY16
SELECT 
LOWER(EMP_NAME) AS EMP_NAME,
TIMESTAMPDIFF(YEAR, JOINING_DATE, CURRENT_DATE_CHECK) AS EXPERIENCE_YEARS,
ROUND(SALARY) AS ROUNDED_SALARY,
DATEDIFF(CURRENT_DATE_CHECK, JOINING_DATE) AS TOTAL_DAYS,
CASE 
WHEN TIMESTAMPDIFF(YEAR, JOINING_DATE, CURRENT_DATE_CHECK) > 10 THEN 'VETERAN'
WHEN TIMESTAMPDIFF(YEAR, JOINING_DATE, CURRENT_DATE_CHECK) BETWEEN 5 AND 10 THEN 'EXPERIENCED'
ELSE 'FRESHER'
END AS EXPERIENCE_STATUS
FROM salary_time_drift;


-- QUERY17
SELECT 
CONCAT(UPPER(LEFT(EMP_NAME,1)), LOWER(SUBSTRING(EMP_NAME,2))) AS EMP_NAME,
TIMESTAMPDIFF(YEAR, JOINING_DATE, CURDATE()) AS ACTUAL_EXPERIENCE,
ABS(DECLARED_EXPERIENCE - TIMESTAMPDIFF(YEAR, JOINING_DATE, CURDATE())) AS EXPERIENCE_DIFF,
FLOOR(SALARY) AS FLOOR_SALARY,
CASE 
WHEN DECLARED_EXPERIENCE > TIMESTAMPDIFF(YEAR, JOINING_DATE, CURDATE()) THEN 'OVERSTATED'
WHEN DECLARED_EXPERIENCE < TIMESTAMPDIFF(YEAR, JOINING_DATE, CURDATE()) THEN 'UNDERSTATED'
ELSE 'MATCHED'
END AS EXPERIENCE_STATUS
FROM employee_experience;


-- QUERY18
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
SALARY + IFNULL(BONUS,0) AS TOTAL_COMPENSATION,
IFNULL(BONUS,0) AS BONUS_AMOUNT,
MONTHNAME(SALARY_DATE) AS SALARY_MONTH,
CASE 
WHEN BONUS IS NULL THEN 'MISSING BONUS'
WHEN (SALARY + IFNULL(BONUS,0)) > 90000 THEN 'HIGH COMPENSATION'
ELSE 'STANDARD'
END AS COMPENSATION_STATUS
FROM salary_integrity;


-- QUERY19
SELECT 
LEFT(EMP_NAME,3) AS FIRST_THREE,
YEAR(JOINING_DATE) AS JOIN_YEAR,
ROUND(SALARY) AS SALARY_ROUNDED,
MOD(ROUND(SALARY),10) AS LAST_DIGIT,
CASE 
WHEN MOD(ROUND(SALARY),10) = MOD(YEAR(JOINING_DATE),10)
THEN 'ENCODE MATCH'
ELSE 'MISMATCH'
END AS ENCODING_STATUS
FROM name_salary;


-- QUERY20
SELECT 
LOWER(EMP_NAME) AS EMP_NAME,
ROUND(ANNUAL_SALARY/12,2) AS MONTHLY_SALARY,
MONTHNAME(PAYMENT_MONTH) AS MONTH,
CEIL(ANNUAL_SALARY/12) AS CEILING_SALARY,
CASE 
WHEN ANNUAL_SALARY/12 >= 100000 THEN 'PREMIUM'
WHEN ANNUAL_SALARY/12 BETWEEN 50000 AND 99999 THEN 'MID RANGE'
ELSE 'BASIC'
END AS SALARY_STATUS
FROM salary_monthly;


-- QUERY21
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
TRUNCATE(SALARY,0) AS TRUNCATED_SALARY,
MOD(TRUNCATE(SALARY,0),10) AS LAST_DIGIT,
DAY(AUDIT_DATE) AS AUDIT_DAY,
CASE 
WHEN MOD(TRUNCATE(SALARY,0),10) = DAY(AUDIT_DATE) THEN 'DIGIT MATCH'
ELSE 'DIGIT MISMATCH'
END AS DIGIT_STATUS
FROM digit_audit;


-- QUERY22
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
DATEDIFF(ACTUAL_CREDIT, EXPECTED_CREDIT) AS DELAY,
ROUND(SALARY) AS SALARY,
DAYNAME(ACTUAL_CREDIT) AS CREDIT_DAY,
CASE 
WHEN DATEDIFF(ACTUAL_CREDIT,EXPECTED_CREDIT) > 5 THEN 'SEVERE DELAY'
WHEN DATEDIFF(ACTUAL_CREDIT,EXPECTED_CREDIT) BETWEEN 1 AND 5 THEN 'MINOR DELAY'
ELSE 'ON TIME'
END AS STATUS
FROM salary_credit_audit;


-- QUERY23
SELECT 
LOWER(EMP_NAME) AS EMP_NAME,
TIMESTAMPDIFF(YEAR, JOINING_DATE, CURRENT_DATE_CHECK) AS EXPERIENCE,
ROUND(SALARY) AS SALARY,
DATEDIFF(CURRENT_DATE_CHECK, JOINING_DATE) AS DAYS,
CASE 
WHEN TIMESTAMPDIFF(YEAR, JOINING_DATE, CURRENT_DATE_CHECK) > 10 THEN 'VETERAN'
WHEN BETWEEN 5 AND 10 THEN 'EXPERIENCED'
ELSE 'FRESHER'
END AS STATUS
FROM salary_time_drift;


-- QUERY24
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
ROUND(SALARY,2) AS SALARY,
MONTHNAME(REVISION_DATE) AS MONTH,
ABS(ROUND(SALARY,2)-TRUNCATE(SALARY,2)) AS DIFF,
CASE 
WHEN ABS(ROUND(SALARY,2)-TRUNCATE(SALARY,2)) > 0 THEN 'LOSS'
ELSE 'STABLE'
END AS STATUS
FROM salary_precision;


-- QUERY25
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
POWER((1+GROWTH_RATE/100),YEARS_PROJECTED)*CURRENT_SALARY AS FUTURE,
ROUND(...) AS ROUNDED,
CASE 
WHEN GROWTH_RATE > 10 THEN 'HIGH'
ELSE 'LOW'
END AS STATUS
FROM salary_growth;


-- QUERY26
SELECT 
LOWER(EMP_NAME) AS EMP_NAME,
REVERSE(SALARY) AS REV,
CASE WHEN SALARY = REVERSE(SALARY) THEN 'YES' ELSE 'NO' END AS STATUS
FROM salary_symmetry;


-- QUERY27
SELECT 
CONCAT(UPPER(LEFT(EMP_NAME,1)),LOWER(SUBSTRING(EMP_NAME,2))) AS EMP_NAME,
CASE WHEN YEAR(PAYMENT_DATE)%4=0 THEN 'LEAP' ELSE 'NORMAL' END
FROM leap_salary;


-- QUERY28
SELECT 
UPPER(EMP_NAME),
DATEDIFF(ACTUAL_CREDIT,EXPECTED_CREDIT),
CASE WHEN DATEDIFF > 5 THEN 'SEVERE' ELSE 'OK' END
FROM salary_credit_audit;


-- QUERY29
SELECT 
UPPER(EMP_NAME),
TIMESTAMPDIFF(YEAR,JOINING_DATE,CURRENT_DATE_CHECK),
CASE WHEN >10 THEN 'VETERAN' ELSE 'FRESHER' END
FROM salary_time_drift;


-- QUERY30
SELECT 
LOWER(EMP_NAME),
ROUND(SALARY),
CASE WHEN MOD(ROUND(SALARY),10)=0 THEN 'MATCH' ELSE 'NO MATCH' END
FROM digit_audit;
