--1
SELECT FULL_NAME , LENGTH(FULL_NAME) ,
CHAR_LENGTH(FULL_NAME) 
FROM employees;

--2
SELECT UPPER(FULL_NAME) AS FULL_NAME ,
LOWER(FULL_NAME) AS FULL_NAME
FROM employees;

--3
SELECT FULL_NAME ,
TRIM(FULL_NAME),
LTRIM(FULL_NAME) ,
RTRIM(FULL_NAME) 
FROM employees;

--4
SELECT 
CONCAT(
  UPPER(LEFT(FULL_NAME,1)),
  LOWER(SUBSTRING(FULL_NAME,2))
  ) AS FULL_NAME,
CONCAT(FULL_NAME , '-' , DEPARTMENT) AS EMP_DETAILS_1
FROM employees;

--5
SELECT CONCAT_WS('|' , EMP_ID , FULL_NAME,CITY) AS EMP_DETAILS_2
FROM employees;

--6
SELECT EMAIL,
SUBSTRING_INDEX(email,'@', -1 ) AS EMAIL_DOMAIN,
SUBSTRING_INDEX(email, '@' , 1) AS username,
SUBSTRING(FULL_NAME , 2, 1 ) AS sec_char
FROM employees;

--7
SELECT FULL_NAME,
LEFT(FULL_NAME,1) ,
RIGHT(FULL_NAME,8)
FROM employees;

--8
SELECT EMAIL ,
INSTR(EMAIL , '@') 
FROM employees;

--9
SELECT EMAIL ,
LOCATE( '.' , EMAIL)
FROM employees;

--10
SELECT FULL_NAME , 
REPLACE(FULL_NAME , 'a' ,'*') AS REPLACED_NAME
FROM employees;

--11
SELECT 
FULL_NAME ,
REVERSE(FULL_NAME) AS REV_FULLNAME
FROM employees;

--12
SELECT FULL_NAME,
LPAD(FULL_NAME , 15, '*') ,
RPAD(FULL_NAME , 15 , '*')
FROM employees;

--13
SELECT CITY ,
TRIM(REPLACE(CITY ,' ','*'))
FROM employees;

--14
SELECT FULL_NAME , REMARKS ,
IFNULL(NULLIF(REMARKS ,' ') , 'NO REMARKS') AS REMARKS
FROM employees;

--15
SELECT FULL_NAME ,REMARKS ,
COALESCE(REMARKS , 'N/A') AS REMARKS
FROM employees;

--16
SELECT 
FIND_IN_SET('Analytics' , 'Data,Analytics,AI') AS SEARCH;
