
-- QUERY31
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
DAYNAME(LOGIN_TIME) AS WEEK_DAY,
TIMESTAMPDIFF(HOUR , LOGIN_TIME , LOGOUT_TIME) AS WORKING_TIME,
TIMESTAMPDIFF(MINUTE ,LOGIN_TIME , LOGOUT_TIME) AS TOTAL_MINUTES,
CASE 
WHEN TIMESTAMPDIFF(HOUR , LOGIN_TIME , LOGOUT_TIME) > 9 THEN 'OVERTIME'
WHEN TIMESTAMPDIFF(HOUR , LOGIN_TIME , LOGOUT_TIME) BETWEEN 7 AND 9 THEN 'REGULAR'
ELSE 'SHORT SHIFT'
END AS WORK_STATUS
FROM employee_login;


-- QUERY32
SELECT 
CONCAT(
  UPPER(LEFT(EMP_NAME,1)),
  LOWER(SUBSTRING(EMP_NAME ,2 ))
) AS EMPLOYEE_NAME,
DAYNAME(CHECK_IN) AS CHECK_IN_WEEKDAY,
TIMESTAMPDIFF(HOUR , CHECK_IN , CHECK_OUT) AS WORKING_HOURS,
ROUND(TIMESTAMPDIFF(HOUR , CHECK_IN , CHECK_OUT) / 60 , 2) AS ROUNDED_WORK_HOURS,
CASE
WHEN HOUR(check_in) > 10 THEN 'Late Entry'
WHEN TIMESTAMPDIFF(HOUR , check_in , check_out) >= 8 THEN 'Full Shift'
ELSE 'Half Shift'
END AS attendance_status
FROM attendance_log;


-- QUERY33
SELECT 
LOWER(EMP_NAME) AS EMP_NAME,
DAYNAME(LOGIN_TIME) AS LOGIN_DAY,
ROUND(ACTIVITY_SCORE) AS ROUNDED_ACTIVITY,
CASE 
WHEN DAYNAME(LOGIN_TIME) IN ('Saturday','Sunday') AND ACTIVITY_SCORE > 80 
THEN 'Suspicious Weekend Activity'
WHEN DAYNAME(LOGIN_TIME) IN ('Saturday','Sunday') 
THEN 'Normal Weekend'
ELSE 'Weekday Activity'
END AS activity_status
FROM weekend_monitor;


-- QUERY34
SELECT 
UPPER(EMP_NAME) AS EMP_NAME,
DAYNAME(LOGIN_TIME) AS LOGIN_DAY,
HOUR(LOGIN_TIME) AS LOGIN_HOUR,
MOD(HOUR(LOGIN_TIME),2) AS LOGIN_MOD,
CASE 
WHEN HOUR(LOGIN_TIME) < 9 THEN 'EARLY LOGIN'
WHEN HOUR(LOGIN_TIME) = 9 THEN 'ON TIME'
ELSE 'LATE LOGIN'
END AS LOGIN_STATUS
FROM login_discipline;


-- QUERY35
SELECT 
CONCAT(
  UPPER(LEFT(EMP_NAME,1)),
  LOWER(SUBSTRING(EMP_NAME,2))
) AS EMP_NAME,
ROUND(PERFORMANCE_SCORE) AS ROUNDED_SCORE,
ABS(PERFORMANCE_SCORE) AS ABSOLUTE_SCORE,
DAYNAME(REVIEW_DATE) AS REVIEW_DAY,
CASE 
WHEN PERFORMANCE_SCORE >= 90 THEN 'EXCELLENT'
WHEN PERFORMANCE_SCORE BETWEEN 75 AND 89 THEN 'GOOD'
ELSE 'AVERAGE'
END AS PERFORMANCE_STATUS
FROM performance_tracker;
