------------------------
+--USING ROW_NUMBER(): +
------------------------
--1
SELECT EMP_ID , EMP_NAME ,
SALARY ,
ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS ROW_NUM
FROM employees;

--2
SELECT EMP_ID , EMP_NAME , DEPARTMENT , SALARY ,
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROW_NUM 
FROM employees;

--3
SELECT EMP_NAME , JOIN_DATE ,
ROW_NUMBER() OVER(ORDER BY JOIN_DATE DESC) AS ROW_NUM
FROM employees;

--4
SELECT EMP_NAME , DEPARTMENT , JOIN_DATE ,
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY JOIN_DATE ASC) AS ROW_NUM
FROM employees;

--5
SELECT ORDER_ID , ORDER_DATE ,
ROW_NUMBER() OVER(ORDER BY ORDER_DATE DESC) AS ROW_NUM
FROM orders;

--6
SELECT ORDER_ID, CITY , AMOUNT ,
ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY AMOUNT DESC) AS ROW_NUM
FROM orders;

--7
SELECT EMP_NAME , SALARY , 
ROW_NUMBER() OVER(ORDER BY SALARY ASC) AS ROW_NUM 
FROM employees;

--8
SELECT EMP_NAME , DEPARTMENT , SALARY ,
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY EMP_NAME) AS ROW_NUM
FROM employees;

-----------------
+--USING RANK(): +
-----------------

--9
SELECT EMP_NAME , SALARY ,
RANK() OVER(ORDER BY SALARY DESC) AS RANKING
FROM employees;

--10
SELECT EMP_NAME , DEPARTMENT , SALARY ,
RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING_IN_DEPT
FROM employees;

--11
SELECT EMP_NAME , JOIN_DATE , 
RANK() OVER(ORDER BY JOIN_DATE DESC) AS RANKING
FROM employees;

--12
SELECT ORDER_ID , AMOUNT ,
RANK() OVER(ORDER BY AMOUNT DESC) AS RANKING
FROM orders;

--13
SELECT ORDER_ID , CITY , AMOUNT ,
RANK() OVER(PARTITION BY CITY ORDER BY AMOUNT DESC) AS RANKING_BY_CITY
FROM orders;

--14
SELECT EMP_NAME , DEPARTMENT , SALARY ,
RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY ASC) AS ASCENDING_RANKING
FROM employees;

--15
SELECT EMP_NAME ,
RANK() OVER(ORDER BY EMP_NAME) AS RANKING
FROM employees;

--16
SELECT ORDER_ID ,CITY, ORDER_DATE ,
RANK() OVER(PARTITION BY CITY ORDER BY ORDER_DATE DESC) AS RANKING
FROM orders;

------------------------
+-- USING DENSE_RANK(): +
------------------------

--17
SELECT EMP_NAME , SALARY , 
DENSE_RANK() OVER(ORDER BY SALARY DESC) AS DENSE_RANKING
FROM employees;

--18
SELECT EMP_NAME , DEPARTMENT , SALARY ,
DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS DENSE_RANKING
FROM employees;

--19
SELECT EMP_NAME , JOIN_DATE ,
DENSE_RANK() OVER(ORDER BY JOIN_DATE DESC) AS DENSE_RANKING
FROM employees;

--20
SELECT ORDER_ID , AMOUNT,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DENSE_RANKING
FROM orders;

--21
SELECT ORDER_ID , CITY , AMOUNT ,
DENSE_RANK() OVER(PARTITION BY CITY ORDER BY AMOUNT DESC) AS DENSE_RANKING
FROM orders;

--22
SELECT EMP_NAME , SALARY ,
DENSE_RANK() OVER(ORDER BY SALARY ASC) AS DENSE_RANKING
FROM employees;

--23
SELECT EMP_NAME , DEPARTMENT ,JOIN_DATE,
DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY JOIN_DATE ASC) AS DENSE_RANKING
FROM employees;

--24
SELECT ORDER_ID , ORDER_DATE ,
DENSE_RANK() OVER(ORDER BY ORDER_DATE DESC) AS DENSE_RANKING
FROM orders;
