--1
SELECT * FROM Employees
WHERE salary IS NULL;

--2
SELECT * FROM Employees 
WHERE bonus IS NOT NULL;

--3
SELECT COUNT(*) AS NO_MANAGER 
FROM Employees 
WHERE MANAGER_ID IS NULL;

--4
SELECT * FROM Employees
WHERE SALARY IS NULL AND BONUS IS NULL;

--5
SELECT * FROM Employees
WHERE SALARY IS NULL AND MANAGER_ID IS NOT NULL;

--6
SELECT EMP_ID , NAME , IFNULL(SALARY,0) AS SALARY 
FROM Employees;

--7
SELECT EMP_ID , NAME , IFNULL(BONUS,1000) AS BONUS
FROM Employees;

--8
SELECT ORDER_ID , CUSTOMER_NAME , IFNULL(AMOUNT , 500) AS AMOUNT
FROM Orders;

--9
SELECT PRODUCT_ID , PRODUCT_NAME , IFNULL(STOCK , 0) AS STOCK
FROM Products;

--10
SELECT EMP_ID , NAME , COALESCE(SALARY , BONUS) AS EARNINGS
FROM Employees;

--11
SELECT EMP_ID , NAME ,COALESCE(SALARY , BONUS , 0) AS INCOME
FROM Employees;

--12
SELECT PRODUCT_ID , PRODUCT_NAME , COALESCE(PRICE , 1000) AS PRICE 
FROM Products;

--13
SELECT ORDER_ID , CUSTOMER_NAME , COALESCE(AMOUNT , DISCOUNT , 0) AS PAYMENT
FROM Orders;

--14
SELECT emp_id , name , NULLIF(SALARY , 0) AS SALARY 
FROM Employees;

--15
SELECT order_id , customer_name , NULLIF(DISCOUNT , 0) AS DISCOUNT 
FROM Orders;

--16
SELECT amount / NULLIF(discount , 0)
FROM Orders;

--17
SELECT ORDER_ID , CUSTOMER_NAME , NULLIF(COUPON_CODE , 'DISC10') AS COUPON_CODE
FROM Orders;

--18
SELECT EMP_ID , NAME , COALESCE(SALARY,0) + COALESCE(BONUS , 0) AS EARNINGS
FROM Employees;

--19
SELECT * FROM Employees 
WHERE SALARY IS NULL AND BONUS IS NULL;

--20
SELECT *  FROM Products
WHERE PRICE IS NULL AND CATEGORY IS NOT NULL;

--21
SELECT * FROM Orders
WHERE AMOUNT IS NULL AND DISCOUNT IS NULL;

--22
SELECT EMP_ID , NAME , COALESCE(SALARY , BONUS , 1000) AS INCOME 
FROM Employees;

--23
SELECT ORDER_ID , CUSTOMER_NAME , NULLIF(AMOUNT , 0) AS AMOUNT 
FROM Orders;

--24
SELECT order_id, ABS(
COALESCE(amount, 0) - COALESCE(discount, 0)
) AS payable
FROM Orders;

--25
SELECT * FROM Employees
WHERE SALARY IS NULL AND MANAGER_ID IS NOT NULL;
