-- 1
SELECT MIXED_VALUE , 
REGEXP_SUBSTR(MIXED_VALUE , '^[0-9]+') AS START_NUMBERS
FROM regex_practice;

-- 2
SELECT MIXED_VALUE , 
REGEXP_SUBSTR(MIXED_VALUE , '[0-9]+$') AS LAST_NUMBERS
FROM regex_practice;

-- 3
SELECT MIXED_VALUE ,
REGEXP_SUBSTR(MIXED_VALUE , '^.') AS FIRST_CHAR
FROM regex_practice;

-- 4
SELECT MIXED_VALUE ,
REGEXP_SUBSTR(MIXED_VALUE , '.$') AS LAST_CHAR
FROM regex_practice;

-- 5
SELECT MIXED_VALUE ,
REGEXP_SUBSTR(MIXED_VALUE , '[0-9]{2}') AS EXACTLY_2_DIGITS
FROM regex_practice;

-- 6
SELECT MIXED_VALUE,
REGEXP_SUBSTR(MIXED_VALUE , '[0-9]') AS NUMBER
FROM regex_practice;

-- 7
SELECT PHONE , 
REGEXP_SUBSTR(PHONE, '[0-9]+') AS COUNTRY_CODE 
FROM regex_practice;

-- 8
SELECT MIXED_VALUE ,
REGEXP_SUBSTR(MIXED_VALUE , '[0-9]+') AS NUMBERS
FROM regex_practice;

-- 9
SELECT EMAIL ,
REGEXP_SUBSTR(EMAIL , '^[^@]+') AS BEFORE_AT
FROM regex_practice;

-- 10
SELECT EMAIL ,
REGEXP_SUBSTR(EMAIL , '@(.+)$') AS AFTER_AT 
FROM regex_practice;

-- 11
SELECT EMAIL , 
REGEXP_SUBSTR(EMAIL , '[^@]+$') AS DOMAIN_NAME 
FROM regex_practice;

-- 12
SELECT EMAIL , 
REGEXP_SUBSTR(EMAIL , '[^.]+$') AS EXTENSION
FROM regex_practice;

-- 13
SELECT MIXED_VALUE ,
REGEXP_SUBSTR(MIXED_VALUE , '[A-Za-z]+') AS ALPHABETS
FROM regex_practice;

-- 14
SELECT MIXED_VALUE , 
REGEXP_SUBSTR(MIXED_VALUE , '[0-9]+') AS NUMBERS
FROM regex_practice;

-- 15
SELECT FULL_TEXT,
REGEXP_SUBSTR(FULL_TEXT , '^...') AS FIRST_3_CHAR 
FROM regex_practice;

-- 16
SELECT FULL_TEXT ,
REGEXP_SUBSTR(FULL_TEXT , '..$') AS LAST_2_CHAR
FROM regex_practice;

-- 17
SELECT FULL_TEXT ,
REGEXP_SUBSTR(FULL_TEXT , '[0-9]+') AS EMPLOYEE_NUMBER
FROM regex_practice;

-- 18
SELECT FULL_TEXT , 
REGEXP_SUBSTR(FULL_TEXT , '[0-9]+$') AS COUNTRY_CODE 
FROM regex_practice;

-- 19
SELECT FULL_TEXT ,
REGEXP_SUBSTR(FULL_TEXT , '_[A-Za-z]+_' ) AS TEXT_BTW_UNDERSCORE
FROM regex_practice;

-- 20
SELECT PHONE ,
REGEXP_SUBSTR(PHONE , '(?<=\\+)[0-9]+') AS COUNTRY_CODE
FROM regex_practice;
